# ICON4Py - ICON inspired code in Python and GT4Py
#
# Copyright (c) 2022-2024, ETH Zurich and MeteoSwiss
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause

"""
JAX primitive for injecting pre-compiled StableHLO (full graupel).

Generated by: tools/generate_qt_update_stablehlo.py → generate_unrolled_transposed.py → generate_combined_graupel.py
"""

import os
import pathlib

import jax
import jax.numpy as jnp
from jax import core as jax_core
from jax._src.lib.mlir import ir
from jax.interpreters import batching, mlir


try:
    from jax.extend.core import Primitive
except (ImportError, AttributeError):
    from jax.core import Primitive

from .definitions import Q


# ============================================================================
# Global configuration
# ============================================================================

_GRAUPEL_HLO_PATH: str | None = None
_USE_GRAUPEL_OPTIMIZED: bool = False
_CACHED_GRAUPEL_HLO: str | None = None
_MERGE_COUNTER = 0


def configure_optimized_graupel(hlo_path: str | None = None, use_optimized: bool = False):
    """Configure the optimized full graupel HLO injection."""
    global _GRAUPEL_HLO_PATH, _USE_GRAUPEL_OPTIMIZED, _CACHED_GRAUPEL_HLO
    _GRAUPEL_HLO_PATH = hlo_path
    _USE_GRAUPEL_OPTIMIZED = use_optimized
    _CACHED_GRAUPEL_HLO = None


def is_graupel_optimized_enabled() -> bool:
    return _USE_GRAUPEL_OPTIMIZED and _GRAUPEL_HLO_PATH is not None


# ============================================================================
# Custom Primitive
# ============================================================================

optimized_graupel_p = Primitive("optimized_graupel_full")
optimized_graupel_p.multiple_results = True


def _graupel_abstract_eval(
    kmin_r, kmin_i, kmin_s, kmin_g, t, p, rho, dz, qv, qc, qr, qs, qi, qg, dt
):
    """Returns 13 f64 arrays of shape (nlev, ncells)."""
    nlev, ncells = t.shape
    f64_shape = jax_core.ShapedArray((nlev, ncells), jnp.float64)

    # 13 outputs: t_final, qv, qc, qr, qs, qi, qg, pflx, pr, ps, pi, pg, eflx
    return tuple([f64_shape] * 13)


def _graupel_impl(kmin_r, kmin_i, kmin_s, kmin_g, t, p, rho, dz, qv, qc, qr, qs, qi, qg, dt):
    """Eager-mode fallback: calls original JAX functions."""
    from ..implementations.graupel_native_transposed import (
        _precipitation_effects_native_transposed_jax,
    )
    from ..implementations.q_t_update_fused import q_t_update_fused

    q_in = Q(v=qv, c=qc, r=qr, s=qs, i=qi, g=qg)
    qnc = 100.0
    last_lev = t.shape[0] - 1

    # Phase 1: q_t_update
    q_updated, t_updated = q_t_update_fused(t, p, rho, q_in, dt, qnc)

    # Phase 2: precipitation_effects
    qr_out, qs_out, qi_out, qg_out, t_final, pflx, pr, ps, pi, pg, eflx = (
        _precipitation_effects_native_transposed_jax(
            last_lev, kmin_r, kmin_i, kmin_s, kmin_g, q_updated, t_updated, rho, dz, dt
        )
    )

    return (
        t_final,
        q_updated.v,
        q_updated.c,
        qr_out,
        qs_out,
        qi_out,
        qg_out,
        pflx,
        pr,
        ps,
        pi,
        pg,
        eflx,
    )


optimized_graupel_p.def_abstract_eval(_graupel_abstract_eval)
optimized_graupel_p.def_impl(_graupel_impl)


# ============================================================================
# MLIR Lowering
# ============================================================================


def _load_graupel_hlo():
    """Load the combined graupel HLO module."""
    global _CACHED_GRAUPEL_HLO
    if _CACHED_GRAUPEL_HLO is not None:
        return _CACHED_GRAUPEL_HLO

    if not _GRAUPEL_HLO_PATH:
        return None

    try:
        path = pathlib.Path(_GRAUPEL_HLO_PATH)
        with open(path) as f:
            _CACHED_GRAUPEL_HLO = f.read()
        print(
            f"[GRAUPEL HLO] Loaded from: {_GRAUPEL_HLO_PATH} ({len(_CACHED_GRAUPEL_HLO)/1024:.0f} KB)"
        )
        return _CACHED_GRAUPEL_HLO
    except Exception as e:
        print(f"[GRAUPEL HLO] Failed to load: {e}")
        return None


def _graupel_lowering(ctx, *args):
    """MLIR lowering: inject StableHLO or fall back to JAX. dt = args[-1]."""
    if is_graupel_optimized_enabled():
        hlo = _load_graupel_hlo()
        if hlo is not None:
            return _stablehlo_injection(ctx, *args)
    return _fallback_lowering(ctx, *args)


def _stablehlo_injection(ctx, *args):
    """Merge pre-compiled StableHLO into the MLIR module."""
    global _CACHED_GRAUPEL_HLO, _MERGE_COUNTER

    hlo_text = _CACHED_GRAUPEL_HLO
    if isinstance(hlo_text, bytes):
        hlo_text = hlo_text.decode("utf-8")

    avals_out = ctx.avals_out
    dst_module = ctx.module_context.module

    try:
        print(f"[GRAUPEL HLO] Parsing StableHLO ({len(hlo_text)} chars)...")
        src_module = ir.Module.parse(hlo_text)
        print("[GRAUPEL HLO] Parsed successfully")

        _MERGE_COUNTER += 1
        desired_name = f"_injected_graupel_{_MERGE_COUNTER}"

        print(f"[GRAUPEL HLO] Merging as '{desired_name}'...")
        actual_name = mlir.merge_mlir_modules(dst_module, desired_name, src_module)
        print(f"[GRAUPEL HLO] Merged as '{actual_name}'")

        from jax._src.lib.mlir.dialects import func as func_dialect

        result_types = [mlir.aval_to_ir_type(aval) for aval in avals_out]

        # dt (args[-1]) is baked into the StableHLO, don't pass it
        call_op = func_dialect.CallOp(
            result_types,
            ir.FlatSymbolRefAttr.get(actual_name),
            list(args[:-1]),
        )
        print("[GRAUPEL HLO] Injection successful!")
        return list(call_op.results)

    except Exception as e:
        print(f"[GRAUPEL HLO] Injection failed: {e}")
        import traceback

        traceback.print_exc()
        return _fallback_lowering(ctx, *args)


def _fallback_lowering(ctx, *args):
    """Inline the original JAX implementation. args[-1] = dt."""
    from ..implementations.graupel_native_transposed import (
        _precipitation_effects_native_transposed_jax,
    )
    from ..implementations.q_t_update_fused import q_t_update_fused

    def full_graupel(kmin_r, kmin_i, kmin_s, kmin_g, t, p, rho, dz, qv, qc, qr, qs, qi, qg, dt):
        q_in = Q(v=qv, c=qc, r=qr, s=qs, i=qi, g=qg)
        qnc = 100.0
        last_lev = t.shape[0] - 1

        q_updated, t_updated = q_t_update_fused(t, p, rho, q_in, dt, qnc)

        qr_out, qs_out, qi_out, qg_out, t_final, pflx, pr, ps, pi, pg, eflx = (
            _precipitation_effects_native_transposed_jax(
                last_lev, kmin_r, kmin_i, kmin_s, kmin_g, q_updated, t_updated, rho, dz, dt
            )
        )

        return (
            t_final,
            q_updated.v,
            q_updated.c,
            qr_out,
            qs_out,
            qi_out,
            qg_out,
            pflx,
            pr,
            ps,
            pi,
            pg,
            eflx,
        )

    lowering_fn = mlir.lower_fun(full_graupel, multiple_results=True)
    return lowering_fn(ctx, *args)


mlir.register_lowering(optimized_graupel_p, _graupel_lowering)


# ============================================================================
# Batching
# ============================================================================


def _graupel_batch(batched_args, batch_dims):
    if all(bd is None for bd in batch_dims):
        return optimized_graupel_p.bind(*batched_args), (None,) * 13

    def unbatched_call(*args):
        return optimized_graupel_p.bind(*args)

    batched_fn = jax.vmap(unbatched_call, in_axes=batch_dims, out_axes=(0,) * 13)
    results = batched_fn(*batched_args)
    return results, (0,) * 13


batching.primitive_batchers[optimized_graupel_p] = _graupel_batch


# ============================================================================
# Auto-configure from environment
# ============================================================================


def auto_configure():
    hlo_path = os.environ.get("MUPHYS_GRAUPEL_HLO")
    use_opt = os.environ.get("MUPHYS_USE_GRAUPEL_OPTIMIZED", "0") == "1"

    if hlo_path and use_opt:
        configure_optimized_graupel(hlo_path=hlo_path, use_optimized=True)
        print(f"[GRAUPEL HLO] Auto-configured from: {hlo_path}")


auto_configure()
